### PR TITLE
Feature/blog posts by authors

### PR DESCRIPTION
**Pull request by ferndopolis**
a WIP @michaelkirk, but i want to get your input on this.

i separated the blog posts by the authors using the directory structure:
/author_name/_posts/a_post.md 

really author_name is treated like a single :category and not :author, apparently jekyll permalinks doesn't accept  :author

so write now when you go to /blog the site you will see all the blog post and the individual blog post link to the authors named route.  

TODO:
make the route blog/author_name list all blog post written by author then we can add the link on the headshots, also will need to style the blog.

### CODE REVIEW

**Comment by ferndopolis** [comment]
@michaelkirk also check my rough draft for my first blog post

**Comment by michaelkirk** [comment]
Nice post fernando! Can you separate the article into a pull request separate from the functional changes to the blog?

**Comment by ferndopolis** [comment]
yeah will do! i saw later yall using articles/ in the branch name

**Comment by lauraerinmann** [comment]
cool post bro!

**Comment by ferndopolis** [comment]
@michaelkirk removed the blog article commit from this PR.  

Looks like Github fixed the behavior which would completely erase all previous comment after doing a force push.

**Comment by michaelkirk** [comment]
@ferndopolis 

I think the reason you are proposing this feature is so we can click through to the blog from the "guild" section of the front page.

My concern there is that not everyone in Jackpine has committed to writing articles. And in the near term, they would be super sparse anyway. I don't think we should have the blog filtered by author until every author has a few posts.

Also, on a minor point, this particular approach would preclude us from using categories as intended.

**Comment by ferndopolis** [comment]
@michaelkirk well wasn't that the original intent to click the image and send you to the author's list of blog articles?

and as for getting more content, /blog will still list all blog articles, so we don't have to immediately roll the individual links off the 'our guild'.  i think from an SEO perspective it would be best to have the blog archive by author now and not switch them later and cause stale links.

beside i was thinking this would encourage more blog entry if we all have your own personal blog area along with the combine one. the personal one being a great place for one to have there free and 'safe' space to voice their solutions to problems solved or whatever they think is worth documenting

**Comment by michaelkirk** [comment]
You've convinced me @ferndopolis! I'm gonna test this to make sure it works how I'd expect, and then I'll merge it in.

**Pull request merged**
